services:
  redis:
    image: redis:7-alpine
    container_name: property-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redispassword}
    restart: unless-stopped
    
  postgres:
    image: postgres:13
    container_name: pgdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=property
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis-data:
    name: property-redis-data
  postgres_data:
    driver: local

networks:
  my_network:
    driver: bridge
